### PR TITLE
Improve travis and test agaisnt clang

### PR DESCRIPTION
**Pull request by Zardoz89**
- Uses the new infrascturure of travis based on container.
- Store on cache cmake and deps
- Test it against g++ 4.9 and clang 3.7

### CODE REVIEW

**Comment by milesrout** [comment]
Looks like travis-ci failed to build the version that was merged in?

**Comment by adam4813** [comment]
Issues with clang still. Visual Studio 2015 is working on clang so I can
soon use that for testing as well.

**Comment by Zardoz89** [comment]
Looks that CLang don't like calling C++ variant of C standard libs (cstdio, cstdlib, etc) on Ubuntu. I read that would be necessary to indicate to clang to use GNU STD C++ lib. If not would be necessary to revise the code and use the C standard libs without std name space. This happens on virtual computer and TEC.

**Comment by Zardoz89** [comment]
See https://github.com/trillek-team/tec/pull/55
I should do it here.

**Pull request merged**
