### PR TITLE
Basic DMA

### PR DESCRIPTION
**Pull request by Zardoz89**
Currently only one device can do DMA at the same time

### CODE REVIEW

**Comment by Zardoz89** [comment]
I try to do a manual merge on my computer. The floppy gets broken with this changes. Plus I got many merging errors by indentation.

**Comment by lundstig** [comment]
Oh, that's not good... Thought the floppy worked with the changes. I'll check it, and try to fix the indentation, I probably forgot to use the right settings when I wrote it :P

**Comment by Zardoz89** [comment]
The indentations should be 4 spaces.

**Comment by Zardoz89** [comment]
Try to use http://editorconfig.org/ with your editor/IDE, as it will auto-setup it for the project.

**Comment by lundstig** [comment]
Thanks, should have time to fix it after school.

**Comment by lundstig** [comment]
I have some tests I need to study to, and will be away all weekend :P 
So it will have to wait until next week.

**Comment by Zardoz89** [comment]
No problem

**Comment by Zardoz89** [comment]
I close this, as it's pretty outdated

**Pull request closed without merging**
